version: '3.8'
services:
  http-server:
    image: http-server
    ports:
      - "8080:8080" 
    environment:
      INTERPRETER_SERVICE: http://interpreter/interpret
    networks:
      - app-network
    depends_on:
      - interpreter
      - ml-engine

  interpreter:
    image: interpreter
    ports:
      - "4000:4000"  
    environment:
      HTTP_SERVER_FEEDBACK: http://http-server/feedback
      ML_ENGINE_EXEC: http://ml-engine/exec
    networks:
      - app-network

  ml-engine:
    image: ml-engine
    ports:
      - "5000:5000"  
    environment:
      HTTP_SERVER_FEEDBACK: http://http-server/feedback
    networks:
      - app-network

networks:
  app-network:
    name: app-network
